services:
  - type: web
    name: auth-service
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: change-me
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: auth-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: auth-redis
          type: redis
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"
    ipAllowList: []
  - type: redis
    name: auth-redis
    plan: free

databases:
  - name: auth-db
    plan: free
